### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by 89z** [joshbarrass/deezerdl#2]
Using this command (with proper ARL):

~~~
.\deezerdl.exe login 0123456789abcde0123456789abcde0123456789abcdefff0123456789a
~~~

I get this result:

~~~
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x18 pc=0x7ce553]

goroutine 1 [running]:
main.main()
        C:/deezerdl-master/cmd/deezerdl.go:65 +0x613
~~~

**Comment by 89z** [comment]
Looks like the problem is here:

https://github.com/joshbarrass/deezerdl/blob/819baf74f340dde2d8407647f3198df94c6ac724/cmd/deezerdl.go#L26-L27

that is not how you instantiate a struct. Proper would be one of these:

~~~go
var config internal.Configuration
var config = internal.Configuration{}
var config = &internal.Configuration{}
var config = new(internal.Configuration)
~~~

**Comment by 89z** [comment]
Look like the problem is here:

https://github.com/joshbarrass/deezerdl/blob/819baf74f340dde2d8407647f3198df94c6ac724/internal/config.go#L66

should be

~~~go
return nil, err
~~~

**Comment by joshbarrass** [comment]
Good spot, I'll amend that ASAP, thanks!

**Comment by 89z** [comment]
Also, this should be `MkdirAll`:

https://github.com/joshbarrass/deezerdl/blob/819baf74f340dde2d8407647f3198df94c6ac724/internal/config.go#L36

to cover Microsoft Windows

**Comment by joshbarrass** [comment]
I've amended the first issue you've highlighted if you want to validate that the problem goes away. I will open a new issue regarding use of `MkdirAll` and resolve that separately.

**Comment by 89z** [comment]
this issue is confirmed fixed
