### ISSUE TITLE
Platform-specific configuration directory

### ISSUE THREAD

**Issue by joshbarrass** [joshbarrass/deezerdl#3]
to cover Microsoft Windows

https://github.com/joshbarrass/deezerdl/blob/819baf74f340dde2d8407647f3198df94c6ac724/internal/config.go#L36

_Originally posted by @89z in https://github.com/joshbarrass/deezerdl/issues/2#issuecomment-790175668_

**Comment by 89z** [comment]
Also, `$HOME` is not portable:

https://github.com/joshbarrass/deezerdl/blob/819baf74f340dde2d8407647f3198df94c6ac724/internal/config.go#L10

Use this instead:

https://golang.org/pkg/os#UserHomeDir

**Comment by joshbarrass** [comment]
I think https://golang.org/pkg/os#UserConfigDir would probably be more appropriate here

**Comment by 89z** [comment]
Agree!

**Comment by joshbarrass** [comment]
Should be resolved by 5e9db820cce25b5ed5e4fd387fd18bc40197320a

**Comment by 89z** [comment]
ironically, now that you are using `UserConfigDir`, `MkdirAll` is no longer required. So you can revert that line if you want, but it shouldnt hurt either way

**Comment by joshbarrass** [comment]
`os.UserConfigDir` was introduced in go 1.13, but this project was originally written for 1.12. I see no reason not to up the required go version, though, so I've done that in b908afa6007e6db6795c2b362bc6f3f3d5cad01d.

**Comment by joshbarrass** [comment]
Aaaaaand upgraded go in the travis config. Fix is confirmed and builds are passing again, closing the issue,.
